### ISSUE TITLE
code cannot be flashed/uploaded

### ISSUE THREAD

**Issue by qurrpurr** [Circuit-Digest/ESP-Drone#7]
I am new to using esp-idf so i may not not know a lot but this error occurs when i tried to build it. 

`CMake Error at run_serial_tool.cmake:56 (message):
  C:/Espressif/python_env/idf4.4_py3.8_env/Scripts/python.exe
  C:/Espressif/frameworks/esp-idf-v4.4/components/esptool_py/esptool/esptool.py
  --chip esp32 failed

FAILED: CMakeFiles/flash
cmd.exe /C "cd /D C:\Espressif\frameworks\esp-idf-v4.4\components\esptool_py && C:\Espressif\tools\cmake\3.20.3\bin\cmake.exe -D IDF_PATH="C:/Espressif/frameworks/esp-idf-v4.4" -D SERIAL_TOOL="C:/Espressif/python_env/idf4.4_py3.8_env/Scripts/python.exe C:/Espressif/frameworks/esp-idf-v4.4/components/esptool_py/esptool/esptool.py --chip esp32" -D SERIAL_TOOL_ARGS="--before=default_reset --after=hard_reset write_flash @flash_args" -D WORKING_DIRECTORY="C:/Espressif/frameworks/esp-idf-v4.4/ESP-Drone/Firmware/esp-drone/build" -P C:/Espressif/frameworks/esp-idf-v4.4/components/esptool_py/run_serial_tool.cmake"
ninja: build stopped: subcommand failed.
ninja failed with exit code 1`

IDF Version: v4.4.
SoC Chip:
Hardware: ESP32_S2_Drone_V1_2

**Comment by qurrpurr** [comment]
turns out i just need to chose the board lol

**Comment by dush123kumar** [comment]
I can give an answer but it's not useful for me by answering it .....
